version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: wiggle_linux_amd64 
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CFLAGS="-I/usr/x86_64-linux-gnu/include $CFLAGS"
      - CPPFLAGS="-I/usr/x86_64-linux-gnu/include $CPPFLAGS"
      - LDFLAGS="-L/usr/x86_64-linux-gnu/lib $LDFLAGS"
      - CGO_LDFLAGS="-L/usr/x86_64-linux-gnu/lib $CGO_LDFLAGS"
      - PKG_CONFIG_PATH=/usr/x86_64-linux-gnu/lib/pkgconfig:$PKG_CONFIG_PATH
    goos:
      - linux
    goarch:
      - amd64
  - id: wiggle_linux_arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CFLAGS="-I/usr/aarch64-linux-gnu/include $CFLAGS"
      - CPPFLAGS="-I/usr/aarch64-linux-gnu/include $CPPFLAGS"
      - LDFLAGS="-L/usr/aarch64-linux-gnu/lib $LDFLAGS"
      - CGO_LDFLAGS="-L/usr/aarch64-linux-gnu/lib $CGO_LDFLAGS"
      - PKG_CONFIG_PATH=/usr/aarch64-linux-gnu/lib/pkgconfig:$PKG_CONFIG_PATH
    goos:
      - linux
    goarch:
      - arm64
  - id: wiggle_darwin_arm64
    env:
      - CGO_ENABLED=1
      #- CC=oa64-clang
      #- CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
  - id: wiggle_darwin_amd64
    env:
      - CGO_ENABLED=1
      #- CC=o64-clang
      #- CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
