name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - run: go mod download
      - name: Install compile deps
        run: |
          sudo apt update
          sudo apt install gcc libc6-dev
          sudo apt install libx11-dev xorg-dev libxtst-dev libpng++-dev
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          sudo apt install libxkbcommon-dev
          sudo apt install xsel xclip
          sudo apt-get install gcc-multilib
          sudo apt-get install gcc-mingw-w64
          sudo apt install libz-mingw-w64-dev
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
