name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - run: go mod download
      - run: |
          sudo apt install gcc-multilib
          sudo apt install gcc-mingw-w64
          # fix err: zlib.h: No such file or directory, Just used by bitmap.
          sudo apt install libz-mingw-w64-dev
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
