name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - run: go mod download
      - name: Install compile deps
        run: |
          sudo apt update
          # gcc
          sudo apt install gcc libc6-dev

          # x11
          sudo apt install libx11-dev xorg-dev libxtst-dev

          # Clipboard
          sudo apt install xsel xclip

          # Bitmap
          sudo apt install libpng++-dev

          # GoHook
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
