name: Release Dry Run
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Install compile deps
        run: |
          sudo apt update
          # gcc
          sudo apt install gcc libc6-dev

          # x11
          sudo apt install libx11-dev xorg-dev libxtst-dev

          # Clipboard
          sudo apt install xsel xclip

          # Bitmap
          sudo apt install libpng++-dev

          # GoHook
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

          # Linux Arm64
          sudo apt install gcc-aarch64-linux-gnu

          # Darwin AMD64
          sudo apt install build-essential
          sudo apt install clang llvm
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
